"""
generate_inventory.py
Insight360 — Executive BI Platform for Retail

Generates fact_inventory_snapshot.csv (weekly store/online inventory
snapshots) from dim_store.csv, dim_product.csv, dim_date.csv, and
fact_sales.csv.

Does not modify: generate_dates.py, generate_stores.py, generate_products.py,
generate_customers.py, generate_sales.py, generate_returns.py
"""

import os
import numpy as np
import pandas as pd

# =================================================
# CONFIG
# =================================================

SEED = 42
TARGET_ROWS = 970_000
NUM_WEEKS = 52

CANDIDATE_DIRS = ["data/raw", "data/cleaned", "data", "."]
PREFERRED_OUTPUT_DIR = "data/raw"

STORE_FILE = "dim_store.csv"
PRODUCT_FILE = "dim_product.csv"
DATE_FILE = "dim_date.csv"
SALES_FILE = "fact_sales.csv"
OUTPUT_FILE = "fact_inventory_snapshot.csv"

# Assortment size (number of SKUs actively tracked) per store format
ASSORTMENT_WEIGHT = {
    "Flagship": 1.6,
    "Express": 1.0,
    "Outlet": 0.8,
    "Online": 2.2,
    "Wholesale": 1.4,
}

# Baseline weekly demand lambda multipliers
FORMAT_DEMAND_FACTOR = {
    "Flagship": 8.0,
    "Express": 4.0,
    "Outlet": 3.0,
    "Online": 6.0,
    "Wholesale": 15.0,
}
DIVISION_DEMAND_FACTOR = {
    "Apparel & Footwear": 1.3,
    "Home & Living": 1.0,
    "Electronics & Accessories": 0.6,
    "Daily Essentials": 1.5,
}

# Regional lead-time / fill-rate distortion (East region bottleneck)
REGION_LEAD_TIME_FACTOR = {
    "East": 2.0,
    "North": 1.0,
    "South": 0.9,
    "West": 1.0,
    "Digital": 1.0,
    "B2B": 1.1,
}
REGION_FILL_RATE = {
    "East": 0.55,
    "North": 0.90,
    "South": 0.92,
    "West": 0.88,
    "Digital": 0.90,
    "B2B": 0.85,
}

# Category (division) distortion — Electronics stockouts more often
DIVISION_FILL_RATE = {
    "Apparel & Footwear": 0.88,
    "Home & Living": 0.90,
    "Electronics & Accessories": 0.60,
    "Daily Essentials": 0.92,
}

FESTIVE_DEMAND_MULTIPLIER = 1.6
FESTIVE_FILL_RATE_PENALTY = 0.75  # multiplied into fill rate during festive weeks

REORDER_TARGET_MULTIPLIER = 2.2   # order-up-to level relative to safety stock


# =================================================
# PATH UTILITIES
# =================================================

def _resolve_input(filename):
    for d in CANDIDATE_DIRS:
        candidate = os.path.join(d, filename)
        if os.path.exists(candidate):
            return candidate
    raise FileNotFoundError(
        f"Could not locate '{filename}' in any of {CANDIDATE_DIRS}. "
        f"Ensure it has been generated by its owning module first."
    )


def _resolve_output_dir():
    try:
        sales_path = _resolve_input(SALES_FILE)
        return os.path.dirname(sales_path) or "."
    except FileNotFoundError:
        os.makedirs(PREFERRED_OUTPUT_DIR, exist_ok=True)
        return PREFERRED_OUTPUT_DIR


def _find_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    raise KeyError(f"None of the expected columns {candidates} found in dataframe.")


# =================================================
# LOAD & PREP
# =================================================

def load_inputs():
    stores = pd.read_csv(_resolve_input(STORE_FILE))
    products = pd.read_csv(_resolve_input(PRODUCT_FILE))
    dates = pd.read_csv(_resolve_input(DATE_FILE))
    sales = pd.read_csv(_resolve_input(SALES_FILE))
    return stores, products, dates, sales


def prepare_dimensions(stores, products, dates):
    store_key_col = _find_col(stores, ["store_key"])
    store_format_col = _find_col(stores, ["store_format"])
    store_region_col = _find_col(stores, ["region"])
    stores = stores.rename(columns={
        store_key_col: "store_key",
        store_format_col: "store_format",
        store_region_col: "region",
    })
    stores["region"] = stores["region"].fillna("North")
    stores["store_format"] = stores["store_format"].fillna("Express")

    product_key_col = _find_col(products, ["product_key"])
    division_col = _find_col(products, ["division"])
    products = products.rename(columns={
        product_key_col: "product_key",
        division_col: "division",
    })
    products["division"] = products["division"].fillna("Daily Essentials")

    date_key_col = _find_col(dates, ["date_key"])
    dates = dates.rename(columns={date_key_col: "date_key"})
    dates["date_key"] = pd.to_datetime(dates["date_key"])

    if "is_festive_period" not in dates.columns:
        dates["is_festive_period"] = dates["date_key"].dt.month.isin([10, 11, 12])

    if "day_of_week" in dates.columns:
        sundays = dates[dates["day_of_week"].astype(str).str.lower() == "sunday"]
    else:
        sundays = dates[dates["date_key"].dt.dayofweek == 6]

    if sundays.empty:
        sundays = dates[dates["date_key"].dt.dayofweek == 6]

    sundays = sundays.sort_values("date_key").drop_duplicates(subset="date_key")
    week_dates = sundays["date_key"].tolist()[:NUM_WEEKS]
    festive_lookup = sundays.set_index("date_key")["is_festive_period"].to_dict()

    return stores, products, week_dates, festive_lookup


def prepare_sales(sales, week_dates):
    sales_store_col = _find_col(sales, ["store_key"])
    sales_product_col = _find_col(sales, ["product_key"])
    sales_date_col = _find_col(sales, ["date_key"])
    sales_qty_col = _find_col(sales, ["quantity"])

    sales = sales.rename(columns={
        sales_store_col: "store_key",
        sales_product_col: "product_key",
        sales_date_col: "date_key",
        sales_qty_col: "quantity",
    })
    sales["date_key"] = pd.to_datetime(sales["date_key"])

    week_bounds = pd.Series(sorted(week_dates))
    sales["week_end"] = pd.cut(
        sales["date_key"],
        bins=[pd.Timestamp.min] + list(week_bounds),
        labels=list(week_bounds),
        right=True,
    )
    sales = sales.dropna(subset=["week_end"])
    sales["week_end"] = pd.to_datetime(sales["week_end"])

    weekly_qty = (
        sales.groupby(["store_key", "product_key", "week_end"])["quantity"]
        .sum()
        .reset_index()
        .rename(columns={"quantity": "sold_qty"})
    )
    return weekly_qty


# =================================================
# ASSORTMENT / PAIR SELECTION
# =================================================

def build_pairs(stores, products, rng):
    n_weeks = NUM_WEEKS
    total_pairs_target = max(1, TARGET_ROWS // n_weeks)

    store_weights = stores["store_format"].map(ASSORTMENT_WEIGHT).fillna(1.0)
    store_weights = store_weights / store_weights.sum()

    n_products = len(products)
    product_index = products["product_key"].to_numpy()

    pairs_per_store = (store_weights * total_pairs_target).round().astype(int)
    pairs_per_store = pairs_per_store.clip(lower=1, upper=n_products)

    pair_rows = []
    for store_key, n_pairs in zip(stores["store_key"], pairs_per_store):
        chosen = rng.choice(product_index, size=int(n_pairs), replace=False)
        pair_rows.append(pd.DataFrame({"store_key": store_key, "product_key": chosen}))

    pairs = pd.concat(pair_rows, ignore_index=True)

    pairs = pairs.merge(stores[["store_key", "store_format", "region"]], on="store_key", how="left")
    pairs = pairs.merge(products[["product_key", "division"]], on="product_key", how="left")

    pairs["region_lead_time"] = pairs["region"].map(REGION_LEAD_TIME_FACTOR).fillna(1.0)
    pairs["region_fill_rate"] = pairs["region"].map(REGION_FILL_RATE).fillna(0.85)
    pairs["division_fill_rate"] = pairs["division"].map(DIVISION_FILL_RATE).fillna(0.85)

    format_factor = pairs["store_format"].map(FORMAT_DEMAND_FACTOR).fillna(4.0)
    division_factor = pairs["division"].map(DIVISION_DEMAND_FACTOR).fillna(1.0)
    baseline_lambda = (format_factor * division_factor).clip(lower=0.5)
    pairs["baseline_weekly_demand"] = baseline_lambda

    pairs["safety_stock"] = np.ceil(
        pairs["baseline_weekly_demand"] * pairs["region_lead_time"]
    ).astype(int).clip(lower=2)

    pairs["reorder_target"] = np.ceil(
        pairs["safety_stock"] * REORDER_TARGET_MULTIPLIER
    ).astype(int)

    pairs["initial_stock"] = np.ceil(
        pairs["safety_stock"] * rng.uniform(1.5, 3.0, size=len(pairs))
    ).astype(int)

    pairs = pairs.reset_index(drop=True)
    pairs["pair_id"] = pairs.index
    return pairs


# =================================================
# WEEKLY SIMULATION (vectorized across pairs, looped across weeks)
# =================================================

def simulate_inventory(pairs, weekly_qty, week_dates, festive_lookup, rng):
    n_pairs = len(pairs)
    opening_stock = pairs["initial_stock"].to_numpy(dtype=np.float64)
    safety_stock = pairs["safety_stock"].to_numpy(dtype=np.float64)
    reorder_target = pairs["reorder_target"].to_numpy(dtype=np.float64)
    baseline_demand = pairs["baseline_weekly_demand"].to_numpy(dtype=np.float64)
    region_fill_rate = pairs["region_fill_rate"].to_numpy(dtype=np.float64)
    division_fill_rate = pairs["division_fill_rate"].to_numpy(dtype=np.float64)
    store_key_arr = pairs["store_key"].to_numpy()
    product_key_arr = pairs["product_key"].to_numpy()

    weekly_qty_indexed = weekly_qty.set_index(["store_key", "product_key", "week_end"])["sold_qty"]

    all_frames = []
    seq_counter = 1

    for week_date in week_dates:
        is_festive = bool(festive_lookup.get(week_date, False))

        lookup_keys = list(zip(store_key_arr, product_key_arr, [week_date] * n_pairs))
        try:
            actual_sales = weekly_qty_indexed.reindex(lookup_keys).to_numpy(dtype=np.float64)
        except Exception:
            actual_sales = np.full(n_pairs, np.nan)
        actual_sales = np.nan_to_num(actual_sales, nan=-1.0)

        simulated_sales = rng.poisson(lam=np.maximum(baseline_demand, 0.1))
        festive_multiplier = FESTIVE_DEMAND_MULTIPLIER if is_festive else 1.0
        simulated_sales = np.ceil(simulated_sales * festive_multiplier).astype(np.float64)

        sales_qty = np.where(actual_sales >= 0, actual_sales, simulated_sales)
        sales_qty = np.maximum(sales_qty, 0)

        replenish_trigger = opening_stock < safety_stock
        base_replenish_qty = np.maximum(reorder_target - opening_stock, 0)

        combined_fill_rate = region_fill_rate * division_fill_rate
        if is_festive:
            combined_fill_rate = combined_fill_rate * FESTIVE_FILL_RATE_PENALTY
        combined_fill_rate = np.clip(combined_fill_rate, 0.05, 1.0)

        fill_noise = rng.uniform(0.85, 1.05, size=n_pairs)
        effective_fill_rate = np.clip(combined_fill_rate * fill_noise, 0.0, 1.0)

        replenished_qty = np.where(
            replenish_trigger,
            np.round(base_replenish_qty * effective_fill_rate),
            0.0,
        )
        replenished_qty = np.maximum(replenished_qty, 0)

        closing_stock = np.maximum(0.0, opening_stock - sales_qty + replenished_qty)

        is_out_of_stock = (closing_stock == 0) | (sales_qty > opening_stock)

        severity = 1.0 - combined_fill_rate
        duration_lambda = 1.0 + severity * 6.0
        stockout_duration = np.where(
            is_out_of_stock,
            np.clip(rng.poisson(lam=duration_lambda), 1, 7),
            0,
        )

        date_str = week_date.strftime("%Y%m%d")
        snapshot_ids = [f"INV-{date_str}-{seq_counter + i:06d}" for i in range(n_pairs)]
        seq_counter += n_pairs

        week_frame = pd.DataFrame({
            "snapshot_id": snapshot_ids,
            "date_key": week_date.strftime("%Y-%m-%d"),
            "store_key": store_key_arr,
            "product_key": product_key_arr,
            "opening_stock": opening_stock.astype(int),
            "sales_qty": sales_qty.astype(int),
            "replenished_qty": replenished_qty.astype(int),
            "closing_stock": closing_stock.astype(int),
            "safety_stock": safety_stock.astype(int),
            "is_out_of_stock": is_out_of_stock,
            "stockout_duration_days": stockout_duration.astype(int),
        })
        all_frames.append(week_frame)

        opening_stock = closing_stock

    result = pd.concat(all_frames, ignore_index=True)
    return result


# =================================================
# VALIDATION
# =================================================

def validate_output(df, stores, products, dates):
    summary = {}

    summary["total_rows"] = len(df)
    summary["duplicate_snapshot_ids"] = int(df["snapshot_id"].duplicated().sum())

    valid_store_keys = set(stores["store_key"])
    valid_product_keys = set(products["product_key"])
    valid_date_keys = set(pd.to_datetime(dates["date_key"]).dt.strftime("%Y-%m-%d"))

    summary["orphan_store_refs"] = int((~df["store_key"].isin(valid_store_keys)).sum())
    summary["orphan_product_refs"] = int((~df["product_key"].isin(valid_product_keys)).sum())
    summary["invalid_date_refs"] = int((~df["date_key"].isin(valid_date_keys)).sum())

    expected_closing = np.maximum(
        0, df["opening_stock"] - df["sales_qty"] + df["replenished_qty"]
    )
    summary["math_consistency_violations"] = int((df["closing_stock"] != expected_closing).sum())

    expected_oos = (df["closing_stock"] == 0) | (df["sales_qty"] > df["opening_stock"])
    summary["oos_flag_violations"] = int((df["is_out_of_stock"] != expected_oos).sum())

    duration_violations = df.loc[df["is_out_of_stock"], "stockout_duration_days"]
    summary["stockout_duration_out_of_range"] = int(
        (~duration_violations.between(1, 7)).sum()
    )
    summary["nonzero_duration_when_not_oos"] = int(
        (df.loc[~df["is_out_of_stock"], "stockout_duration_days"] != 0).sum()
    )

    summary["overall_stockout_rate"] = float(df["is_out_of_stock"].mean())

    df_with_region = df.merge(stores[["store_key", "region"]], on="store_key", how="left")
    summary["stockout_rate_by_region"] = (
        df_with_region.groupby("region")["is_out_of_stock"].mean().round(4).to_dict()
    )

    df_with_division = df.merge(products[["product_key", "division"]], on="product_key", how="left")
    summary["stockout_rate_by_division"] = (
        df_with_division.groupby("division")["is_out_of_stock"].mean().round(4).to_dict()
    )

    return summary


def print_validation_summary(summary):
    print("=" * 60)
    print("FACT_INVENTORY_SNAPSHOT — VALIDATION SUMMARY")
    print("=" * 60)
    print(f"Total rows generated       : {summary['total_rows']:,}")
    print(f"Duplicate snapshot_ids     : {summary['duplicate_snapshot_ids']}")
    print(f"Orphan store_key refs      : {summary['orphan_store_refs']}")
    print(f"Orphan product_key refs    : {summary['orphan_product_refs']}")
    print(f"Invalid date_key refs      : {summary['invalid_date_refs']}")
    print(f"Math consistency violations: {summary['math_consistency_violations']}")
    print(f"is_out_of_stock violations : {summary['oos_flag_violations']}")
    print(f"Stockout duration range viol.: {summary['stockout_duration_out_of_range']}")
    print(f"Nonzero duration when in-stock: {summary['nonzero_duration_when_not_oos']}")
    print(f"Overall stockout rate      : {summary['overall_stockout_rate']:.2%}")
    print("Stockout rate by region:")
    for region, rate in summary["stockout_rate_by_region"].items():
        print(f"   - {region:10s}: {rate:.2%}")
    print("Stockout rate by division:")
    for division, rate in summary["stockout_rate_by_division"].items():
        print(f"   - {division:28s}: {rate:.2%}")
    print("=" * 60)


# =================================================
# MAIN
# =================================================

def main():
    rng = np.random.default_rng(SEED)

    stores_raw, products_raw, dates_raw, sales_raw = load_inputs()
    stores, products, week_dates, festive_lookup = prepare_dimensions(
        stores_raw, products_raw, dates_raw
    )
    weekly_qty = prepare_sales(sales_raw, week_dates)

    pairs = build_pairs(stores, products, rng)
    inventory_df = simulate_inventory(pairs, weekly_qty, week_dates, festive_lookup, rng)

    assert inventory_df["snapshot_id"].is_unique, "Duplicate snapshot_id detected."

    output_dir = _resolve_output_dir()
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, OUTPUT_FILE)
    inventory_df.to_csv(output_path, index=False)

    summary = validate_output(inventory_df, stores, products, dates_raw)
    print_validation_summary(summary)
    print(f"fact_inventory_snapshot.csv written to: {output_path} ({len(inventory_df):,} rows)")


if __name__ == "__main__":
    main()