"""
generate_returns.py
Insight360 -- Executive BI Platform for Retail

Generates fact_returns.csv from fact_sales.csv (plus dim_date, dim_store,
dim_product for validation and business-rule inputs), then updates
fact_sales.csv in place by setting return_flag=True on returned sales.

Does NOT modify: generate_dates.py, generate_stores.py, generate_products.py,
generate_customers.py, generate_sales.py
"""

import os
import numpy as np
import pandas as pd

# =================================================
# CONFIG
# =================================================

SEED = 42
TARGET_RETURN_COUNT = 220_000

# Channel weighting -> relative return-rate multipliers
STORE_WEIGHT = 1.0
ONLINE_WEIGHT = 1.8          # within required 1.6-2.0x Store
WHOLESALE_WEIGHT = 0.02      # near-zero

MAX_RETURN_WINDOW_DAYS = 30
FULL_RETURN_PROB = 0.70               # probability a return covers the full sold quantity
RESTOCK_PROB_NON_DEFECTIVE = 0.85     # P(is_restocked=True | reason != Defective/Damaged)

CANDIDATE_DIRS = ["data/cleaned", "data/raw", "data", "."]

SALES_FILE = "fact_sales.csv"
DATE_FILE = "dim_date.csv"
STORE_FILE = "dim_store.csv"
PRODUCT_FILE = "dim_product.csv"
RETURNS_OUTPUT_FILE = "fact_returns.csv"

REQUIRED_RETURN_COLUMNS = [
    "return_id",
    "original_sales_id",
    "date_key",
    "product_key",
    "store_key",
    "quantity_returned",
    "return_reason",
    "refund_amount",
    "is_restocked",
]

# Return-reason distributions, keyed by product division.
REASON_POOLS = {
    "Apparel & Footwear": {
        "Size/Fit Issue": 0.65,
        "Changed Mind": 0.13,
        "Defective/Damaged": 0.10,
        "Wrong Item Delivered": 0.07,
        "Quality Not as Expected": 0.05,
    },
    "Electronics & Accessories": {
        "Defective/Damaged": 0.60,
        "Wrong Item Delivered": 0.14,
        "Changed Mind": 0.12,
        "Quality Not as Expected": 0.09,
        "Size/Fit Issue": 0.05,
    },
    "Home & Living": {
        "Changed Mind": 0.58,
        "Quality Not as Expected": 0.16,
        "Defective/Damaged": 0.14,
        "Wrong Item Delivered": 0.07,
        "Size/Fit Issue": 0.05,
    },
    "Daily Essentials": {
        "Other": 0.52,
        "Quality Not as Expected": 0.19,
        "Defective/Damaged": 0.16,
        "Changed Mind": 0.09,
        "Wrong Item Delivered": 0.04,
    },
}
DEFAULT_REASON_POOL = {
    "Other": 0.40,
    "Changed Mind": 0.25,
    "Defective/Damaged": 0.15,
    "Quality Not as Expected": 0.12,
    "Size/Fit Issue": 0.08,
}


# =================================================
# PATH / SCHEMA UTILITIES
# =================================================

def _resolve_path(filename):
    for d in CANDIDATE_DIRS:
        candidate = os.path.join(d, filename)
        if os.path.exists(candidate):
            return candidate
    raise FileNotFoundError(
        f"Could not locate '{filename}' in any of {CANDIDATE_DIRS}. "
        f"Ensure it has already been generated by its owning module."
    )


def _find_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    raise KeyError(f"None of the expected columns {candidates} found. Available: {list(df.columns)}")


def load_inputs():
    sales = pd.read_csv(_resolve_path(SALES_FILE))
    dates = pd.read_csv(_resolve_path(DATE_FILE))
    stores = pd.read_csv(_resolve_path(STORE_FILE))
    products = pd.read_csv(_resolve_path(PRODUCT_FILE))
    return sales, dates, stores, products


# =================================================
# PREPARATION
# =================================================

def prepare_sales(raw_sales, dates, stores, products):
    """Normalize column names and attach helper fields needed for return generation."""
    sales_id_col = _find_col(raw_sales, ["sales_id", "sales_line_id"])
    date_col = _find_col(raw_sales, ["date_key"])
    store_col = _find_col(raw_sales, ["store_key"])
    product_col = _find_col(raw_sales, ["product_key"])
    qty_col = _find_col(raw_sales, ["quantity"])
    net_sales_col = _find_col(raw_sales, ["net_sales_amount", "net_sales", "sales_amount"])

    sales = raw_sales.rename(
        columns={
            sales_id_col: "sales_id",
            date_col: "date_key",
            store_col: "store_key",
            product_col: "product_key",
            qty_col: "quantity",
            net_sales_col: "net_sales_amount",
        }
    ).copy()

    sales["date_key"] = pd.to_datetime(sales["date_key"])

    date_key_col = _find_col(dates, ["date_key"])
    dates = dates.copy()
    dates[date_key_col] = pd.to_datetime(dates[date_key_col])
    valid_dates = set(dates[date_key_col])
    max_date = dates[date_key_col].max()

    # Resolve channel (Store / Online / Wholesale)
    if "channel" in sales.columns:
        channel = sales["channel"].astype(str)
    else:
        store_key_col = _find_col(stores, ["store_key"])
        store_format_col = _find_col(stores, ["store_format", "channel"])
        store_channel_map = stores.set_index(store_key_col)[store_format_col].to_dict()
        channel = sales["store_key"].map(store_channel_map).astype(str)
        channel = channel.replace({"Flagship": "Store", "Express": "Store", "Outlet": "Store"})
    sales["_channel"] = channel

    # Attach product division (drives return-reason distribution)
    product_key_col = _find_col(products, ["product_key"])
    division_col = _find_col(products, ["division"])
    product_division_map = products.set_index(product_key_col)[division_col].to_dict()
    sales["_division"] = sales["product_key"].map(product_division_map).fillna("Unknown")

    sales_id_col_name = sales_id_col
    return sales, valid_dates, max_date, sales_id_col_name


# =================================================
# ELIGIBILITY + SAMPLING
# =================================================

def build_eligible_pool(sales, max_date):
    """Sales eligible for a return: positive quantity, and at least 1 day has
    elapsed since the sale relative to the simulation's latest date."""
    eligible = sales[sales["quantity"] > 0].copy()
    days_since_sale = (max_date - eligible["date_key"]).dt.days
    eligible = eligible[days_since_sale >= 1].copy()
    eligible["_days_available"] = days_since_sale[days_since_sale >= 1].clip(upper=MAX_RETURN_WINDOW_DAYS)
    return eligible


def select_returned_rows(eligible, rng):
    """Sample rows for return via per-channel target counts, so the resulting
    channel-level return RATES respect the required ratios exactly, then draw
    uniformly (fast, unweighted) without replacement within each channel."""
    channel_weights = {"Store": STORE_WEIGHT, "Online": ONLINE_WEIGHT, "Wholesale": WHOLESALE_WEIGHT}

    counts = eligible["_channel"].value_counts().to_dict()
    weighted_total = sum(channel_weights.get(ch, STORE_WEIGHT) * n for ch, n in counts.items())
    if weighted_total <= 0:
        raise ValueError("No eligible sales available for return generation.")

    scale = min(TARGET_RETURN_COUNT / weighted_total, 1.0) if weighted_total else 0.0

    selected_frames = []
    for channel, group in eligible.groupby("_channel"):
        weight = channel_weights.get(channel, STORE_WEIGHT)
        n_select = int(round(len(group) * weight * scale))
        n_select = min(n_select, len(group))
        if n_select <= 0:
            continue
        chosen_positions = rng.choice(len(group), size=n_select, replace=False)
        selected_frames.append(group.iloc[chosen_positions])

    if not selected_frames:
        raise ValueError("Return selection produced zero rows; check channel weights/config.")

    selected = pd.concat(selected_frames, axis=0)

    # Trim/adjust to stay close to the target count without exceeding eligible pool.
    if len(selected) > TARGET_RETURN_COUNT:
        drop_idx = rng.choice(selected.index.to_numpy(), size=len(selected) - TARGET_RETURN_COUNT, replace=False)
        selected = selected.drop(index=drop_idx)

    return selected.copy()


# =================================================
# ATTRIBUTE GENERATION (vectorized)
# =================================================

def assign_return_dates(selected, rng):
    days_available = selected["_days_available"].to_numpy(dtype=np.int64)
    offsets = rng.integers(low=1, high=days_available + 1)
    selected["return_date"] = selected["date_key"].to_numpy() + pd.to_timedelta(offsets, unit="D")
    return selected


def assign_quantity_returned(selected, rng):
    qty_sold = selected["quantity"].to_numpy()
    full_return = rng.random(len(selected)) < FULL_RETURN_PROB

    safe_upper = np.maximum(qty_sold, 2)
    partial_qty = np.where(qty_sold > 1, rng.integers(low=1, high=safe_upper), 1)

    qty_returned = np.where(full_return, qty_sold, partial_qty)
    qty_returned = np.clip(qty_returned, 1, qty_sold)
    selected["quantity_returned"] = qty_returned
    return selected


def assign_refund_amount(selected):
    qty_sold_safe = selected["quantity"].replace(0, np.nan).astype(float)
    proportion = selected["quantity_returned"].astype(float) / qty_sold_safe
    refund = (selected["net_sales_amount"].astype(float) * proportion).round(2)
    refund = np.minimum(refund, selected["net_sales_amount"].astype(float))
    selected["refund_amount"] = refund.fillna(0.0).clip(lower=0.0)
    return selected


def assign_return_reason(selected, rng):
    reasons = np.empty(len(selected), dtype=object)
    divisions = selected["_division"].to_numpy()

    for division in pd.unique(divisions):
        mask = divisions == division
        pool = REASON_POOLS.get(division, DEFAULT_REASON_POOL)
        labels = list(pool.keys())
        weights = np.array(list(pool.values()), dtype=np.float64)
        weights = weights / weights.sum()
        reasons[mask] = rng.choice(labels, size=mask.sum(), p=weights)

    selected["return_reason"] = reasons
    return selected


def assign_restock_flag(selected, rng):
    is_defective = selected["return_reason"] == "Defective/Damaged"
    restock_roll = rng.random(len(selected)) < RESTOCK_PROB_NON_DEFECTIVE
    selected["is_restocked"] = np.where(is_defective, False, restock_roll)
    return selected


def build_return_ids(selected):
    """Format: RT-YYYYMMDD-NNNNNN, sequence unique within each return date."""
    selected = selected.sort_values(["return_date"]).copy()
    date_strs = selected["return_date"].dt.strftime("%Y%m%d")
    seq = selected.groupby(date_strs).cumcount() + 1
    selected["return_id"] = ["RT-" + d + "-" + f"{s:06d}" for d, s in zip(date_strs.to_numpy(), seq.to_numpy())]
    return selected


# =================================================
# VALIDATION
# =================================================

def validate_returns(returns_df, valid_sales_ids, valid_dates):
    assert returns_df["return_id"].is_unique, "Duplicate return_id detected."

    orphan_mask = ~returns_df["original_sales_id"].isin(valid_sales_ids)
    assert not orphan_mask.any(), "Orphan sales references detected in fact_returns."

    invalid_date_mask = ~returns_df["date_key"].isin(valid_dates)
    assert not invalid_date_mask.any(), "Invalid return dates detected (not present in dim_date)."

    assert (returns_df["quantity_returned"] > 0).all(), "Non-positive quantity_returned detected."
    assert (returns_df["quantity_returned"] <= returns_df["_quantity_sold"]).all(), \
        "quantity_returned exceeds quantity sold."

    assert (returns_df["refund_amount"] >= 0).all(), "Negative refund_amount detected."
    assert (returns_df["refund_amount"] <= returns_df["_net_sales_amount"] + 0.01).all(), \
        "refund_amount exceeds original net sales amount."

    assert (returns_df["date_key"] > returns_df["_original_sale_date"]).all(), \
        "Return date does not fall after the original sale date."

    window_days = (returns_df["date_key"] - returns_df["_original_sale_date"]).dt.days
    assert (window_days <= MAX_RETURN_WINDOW_DAYS).all(), "Return date exceeds 30-day return window."


# =================================================
# OUTPUT
# =================================================

def finalize_returns_output(selected):
    output = pd.DataFrame(
        {
            "return_id": selected["return_id"],
            "original_sales_id": selected["sales_id"],
            "date_key": selected["return_date"].dt.strftime("%Y-%m-%d"),
            "product_key": selected["product_key"],
            "store_key": selected["store_key"],
            "quantity_returned": selected["quantity_returned"].astype(int),
            "return_reason": selected["return_reason"],
            "refund_amount": selected["refund_amount"].round(2),
            "is_restocked": selected["is_restocked"].astype(bool),
        }
    )
    return output[REQUIRED_RETURN_COLUMNS]


def update_sales_with_return_flag(raw_sales, sales_id_col_name, sales_id_series, returned_sales_ids):
    sales_out = raw_sales.copy()
    sales_out["return_flag"] = sales_id_series.isin(returned_sales_ids)
    return sales_out


# =================================================
# MAIN
# =================================================

def main():
    rng = np.random.default_rng(SEED)

    raw_sales, dates, stores, products = load_inputs()
    sales, valid_dates, max_date, sales_id_col_name = prepare_sales(raw_sales, dates, stores, products)

    eligible = build_eligible_pool(sales, max_date)
    selected = select_returned_rows(eligible, rng)

    selected = assign_return_dates(selected, rng)
    selected = assign_quantity_returned(selected, rng)
    selected = assign_refund_amount(selected)
    selected = assign_return_reason(selected, rng)
    selected = assign_restock_flag(selected, rng)
    selected = build_return_ids(selected)

    # Assemble a validation frame (keeps helper/raw fields needed for checks)
    validation_frame = selected.copy()
    validation_frame["original_sales_id"] = validation_frame["sales_id"]
    validation_frame["date_key"] = validation_frame["return_date"]
    validation_frame["_quantity_sold"] = validation_frame["quantity"]
    validation_frame["_net_sales_amount"] = validation_frame["net_sales_amount"]
    validation_frame["_original_sale_date"] = selected["date_key"]

    valid_sales_ids = set(sales["sales_id"])
    validate_returns(validation_frame, valid_sales_ids, valid_dates)

    returns_output = finalize_returns_output(selected)

    # Final integrity re-check on the exact file that will be written
    assert returns_output["return_id"].is_unique, "Duplicate return_id in final output."
    assert not returns_output["original_sales_id"].isna().any(), "Null original_sales_id in final output."
    assert (returns_output["quantity_returned"] > 0).all()
    assert (returns_output["refund_amount"] >= 0).all()

    returns_out_path = os.path.join(os.path.dirname(_resolve_path(SALES_FILE)), RETURNS_OUTPUT_FILE)
    returns_output.to_csv(returns_out_path, index=False)

    updated_sales = update_sales_with_return_flag(
        raw_sales, sales_id_col_name, sales["sales_id"], set(selected["sales_id"])
    )
    sales_out_path = _resolve_path(SALES_FILE)
    updated_sales.to_csv(sales_out_path, index=False)

    print(f"fact_returns.csv written to: {returns_out_path} ({len(returns_output):,} rows)")
    print(
        f"fact_sales.csv updated in place: {sales_out_path} "
        f"({int(updated_sales['return_flag'].sum()):,} rows flagged as returned)"
    )


if __name__ == "__main__":
    main()
