"""
generate_staffing.py
Insight360 -- Executive BI Platform for Retail

Generates fact_staffing.csv (store-week grain) for physical stores only,
using dim_store.csv and dim_date.csv as inputs.

Does NOT modify: generate_dates.py, generate_stores.py, generate_products.py,
generate_customers.py, generate_sales.py, generate_returns.py,
generate_inventory.py

ASSUMPTION: fact_sales.csv is not among this module's declared inputs
(only dim_store.csv and dim_date.csv are). sales_per_labor_hour is therefore
derived from a store-format + square-footage based synthetic weekly revenue
proxy (with a regional adjustment and a festive-season multiplier), not from
actual transactional data. If real fact_sales figures should drive this KPI
instead, a downstream reconciliation step can recompute it from fact_sales.csv.
"""

import os
import numpy as np
import pandas as pd

# =================================================
# CONFIG
# =================================================

SEED = 42

TARGET_PHYSICAL_STORES = 214
TARGET_WEEKS = 52
TARGET_ROWS = TARGET_PHYSICAL_STORES * TARGET_WEEKS  # 11,128

PHYSICAL_FORMATS = {"Flagship", "Express", "Outlet"}
NON_PHYSICAL_FORMATS = {"Online", "Wholesale", "Digital", "B2B"}

# Format-based allocated-headcount ranges
HEADCOUNT_RANGES = {
    "Flagship": (25, 45),
    "Express": (8, 18),
    "Outlet": (10, 22),
}

AVG_HOURS_PER_EMPLOYEE = 40.0        # baseline scheduled hours/employee/week
SCHEDULED_HOURS_NOISE = 0.06         # +/- variation around the baseline

# Festive-period (Oct-Dec / Diwali season) multipliers
FESTIVE_MONTHS = {10, 11, 12}
FESTIVE_SCHEDULED_HOURS_BOOST = (0.15, 0.30)   # +15% to +30% scheduled hours
FESTIVE_ACTUAL_HEADCOUNT_BOOST = (0.05, 0.15)  # temp/seasonal staff bump
FESTIVE_OVERTIME_SHARE = (0.15, 0.35)          # overtime as a share of scheduled hours
NON_FESTIVE_OVERTIME_SHARE = (0.02, 0.08)

HOURLY_RATE_RANGE_BY_FORMAT = {
    "Flagship": (22, 28),
    "Express": (18, 24),
    "Outlet": (18, 23),
}
OVERTIME_MULTIPLIER = 1.5
LABOR_OVERHEAD_RATE = 0.12   # benefits/payroll-tax style overhead on wage cost

# Synthetic weekly revenue proxy (store-format based), used only to derive
# sales_per_labor_hour since fact_sales.csv is not an input to this module.
WEEKLY_REVENUE_RANGE_BY_FORMAT = {
    "Flagship": (6_000_000, 12_000_000),
    "Express": (2_000_000, 4_500_000),
    "Outlet": (1_200_000, 3_000_000),
}
FESTIVE_REVENUE_MULTIPLIER = (1.30, 1.65)
EAST_REGION_REVENUE_PENALTY = 0.85   # East underperformance, consistent with prior phases

CANDIDATE_DIRS = ["data/raw", "data/cleaned", "data", "."]

STORE_FILE = "dim_store.csv"
DATE_FILE = "dim_date.csv"
STAFFING_OUTPUT_FILE = "fact_staffing.csv"


# =================================================
# PATH / SCHEMA UTILITIES
# =================================================

def _resolve_path(filename):
    for d in CANDIDATE_DIRS:
        candidate = os.path.join(d, filename)
        if os.path.exists(candidate):
            return candidate
    raise FileNotFoundError(
        f"Could not locate '{filename}' in any of {CANDIDATE_DIRS}. "
        f"Ensure it has already been generated by its owning module."
    )


def _find_col(df, candidates, required=True):
    for c in candidates:
        if c in df.columns:
            return c
    if required:
        raise KeyError(f"None of the expected columns {candidates} found. Available: {list(df.columns)}")
    return None


def load_inputs():
    stores = pd.read_csv(_resolve_path(STORE_FILE))
    dates = pd.read_csv(_resolve_path(DATE_FILE))
    return stores, dates


# =================================================
# PREPARATION -- STORES
# =================================================

def prepare_physical_stores(raw_stores):
    store_key_col = _find_col(raw_stores, ["store_key"])
    format_col = _find_col(raw_stores, ["store_format", "format"])
    region_col = _find_col(raw_stores, ["region"], required=False)
    sqft_col = _find_col(raw_stores, ["sqft"], required=False)

    stores = raw_stores.copy()
    stores = stores[~stores[format_col].isin(NON_PHYSICAL_FORMATS)].copy()
    stores = stores[stores[format_col].isin(PHYSICAL_FORMATS)].copy()

    stores = stores.rename(columns={store_key_col: "store_key", format_col: "store_format"})
    if region_col:
        stores = stores.rename(columns={region_col: "region"})
    else:
        stores["region"] = "Unknown"
    if sqft_col:
        stores = stores.rename(columns={sqft_col: "sqft"})
    else:
        stores["sqft"] = np.nan

    stores = stores[["store_key", "store_format", "region", "sqft"]].drop_duplicates(subset=["store_key"])
    return stores.reset_index(drop=True)


def assign_store_level_attributes(stores, rng):
    """Attributes that stay constant for a given store across all weeks:
    its staffing-plan headcount baseline and its base hourly wage rate."""
    stores = stores.copy()

    hc_low = stores["store_format"].map(lambda f: HEADCOUNT_RANGES.get(f, (10, 20))[0])
    hc_high = stores["store_format"].map(lambda f: HEADCOUNT_RANGES.get(f, (10, 20))[1])
    stores["allocated_headcount_base"] = rng.integers(hc_low.to_numpy(), hc_high.to_numpy() + 1)

    rate_low = stores["store_format"].map(lambda f: HOURLY_RATE_RANGE_BY_FORMAT.get(f, (18, 24))[0])
    rate_high = stores["store_format"].map(lambda f: HOURLY_RATE_RANGE_BY_FORMAT.get(f, (18, 24))[1])
    stores["hourly_rate"] = rng.uniform(rate_low.to_numpy(), rate_high.to_numpy()).round(2)

    rev_low = stores["store_format"].map(lambda f: WEEKLY_REVENUE_RANGE_BY_FORMAT.get(f, (1_000_000, 2_000_000))[0])
    rev_high = stores["store_format"].map(lambda f: WEEKLY_REVENUE_RANGE_BY_FORMAT.get(f, (1_000_000, 2_000_000))[1])
    # sqft-informed scaling within the format's revenue band, when sqft is available
    sqft_factor = stores["sqft"].astype(float)
    if sqft_factor.notna().any():
        fmt_sqft_mean = stores.groupby("store_format")["sqft"].transform("mean")
        relative_size = (sqft_factor / fmt_sqft_mean).fillna(1.0).clip(0.6, 1.6)
    else:
        relative_size = pd.Series(1.0, index=stores.index)
    base_weekly_revenue = rng.uniform(rev_low.to_numpy(), rev_high.to_numpy())
    stores["base_weekly_revenue"] = (base_weekly_revenue * relative_size.to_numpy()).round(2)

    region_penalty = np.where(stores["region"] == "East", EAST_REGION_REVENUE_PENALTY, 1.0)
    stores["base_weekly_revenue"] = (stores["base_weekly_revenue"] * region_penalty).round(2)

    return stores


# =================================================
# PREPARATION -- WEEKS
# =================================================

def prepare_weeks(raw_dates):
    date_key_col = _find_col(raw_dates, ["date_key"])
    fiscal_year_col = _find_col(raw_dates, ["fiscal_year"], required=False)
    is_festive_col = _find_col(raw_dates, ["is_festive_period"], required=False)

    dates = raw_dates.copy()
    dates[date_key_col] = pd.to_datetime(dates[date_key_col])
    dates = dates.rename(columns={date_key_col: "date_key"})

    dates["_week_start"] = dates["date_key"] - pd.to_timedelta(dates["date_key"].dt.weekday, unit="D")
    dates["_month"] = dates["date_key"].dt.month

    if is_festive_col and is_festive_col in dates.columns:
        dates = dates.rename(columns={is_festive_col: "_is_festive_day"})
        dates["_is_festive_day"] = dates["_is_festive_day"].astype(bool)
    else:
        dates["_is_festive_day"] = dates["_month"].isin(FESTIVE_MONTHS)

    dates["_is_festive_day"] = dates["_is_festive_day"] | dates["_month"].isin(FESTIVE_MONTHS)

    week_agg = dates.groupby("_week_start").agg(
        is_festive_week=("_is_festive_day", "any"),
        days_in_week=("date_key", "count"),
    ).reset_index().rename(columns={"_week_start": "week_start"})

    week_agg = week_agg.sort_values("week_start").reset_index(drop=True)

    if fiscal_year_col and fiscal_year_col in dates.columns:
        fy_by_week = dates.groupby("_week_start")[fiscal_year_col].agg(lambda s: s.value_counts().idxmax())
        week_agg["fiscal_year"] = week_agg["week_start"].map(fy_by_week)
        target_fy = week_agg["fiscal_year"].max()
        chosen = week_agg[week_agg["fiscal_year"] == target_fy].copy()
    else:
        chosen = week_agg.copy()

    # Take exactly TARGET_WEEKS most recent full weeks available for the chosen year/window
    chosen = chosen.sort_values("week_start")
    if len(chosen) > TARGET_WEEKS:
        chosen = chosen.tail(TARGET_WEEKS)
    chosen = chosen.reset_index(drop=True)

    return chosen[["week_start", "is_festive_week"]], set(dates["date_key"])


# =================================================
# GRID CONSTRUCTION + METRIC ASSIGNMENT
# =================================================

def build_grid(stores, weeks):
    stores = stores.copy()
    weeks = weeks.copy()
    stores["_key"] = 1
    weeks["_key"] = 1
    grid = stores.merge(weeks, on="_key").drop(columns="_key")
    grid = grid.rename(columns={"week_start": "date_key"})
    return grid.reset_index(drop=True)


def assign_headcount(grid, rng):
    n = len(grid)

    weekly_noise = rng.integers(-1, 2, size=n)  # small +/-1 weekly fluctuation
    grid["allocated_headcount"] = (grid["allocated_headcount_base"] + weekly_noise).clip(lower=3).astype(int)

    attendance_factor = rng.uniform(0.85, 1.05, size=n)
    festive_bump = np.where(
        grid["is_festive_week"],
        1.0 + rng.uniform(*FESTIVE_ACTUAL_HEADCOUNT_BOOST, size=n),
        1.0,
    )
    grid["actual_headcount"] = np.round(
        grid["allocated_headcount"].to_numpy() * attendance_factor * festive_bump
    ).clip(min=1).astype(int)

    return grid


def assign_hours(grid, rng):
    n = len(grid)

    base_scheduled = grid["actual_headcount"].to_numpy() * AVG_HOURS_PER_EMPLOYEE
    noise = rng.uniform(1 - SCHEDULED_HOURS_NOISE, 1 + SCHEDULED_HOURS_NOISE, size=n)
    festive_boost = np.where(
        grid["is_festive_week"],
        1.0 + rng.uniform(*FESTIVE_SCHEDULED_HOURS_BOOST, size=n),
        1.0,
    )
    grid["scheduled_hours"] = (base_scheduled * noise * festive_boost).round(1)

    actual_factor = rng.uniform(0.95, 1.08, size=n)
    grid["actual_hours"] = (grid["scheduled_hours"] * actual_factor).round(1)

    overtime_share = np.where(
        grid["is_festive_week"],
        rng.uniform(*FESTIVE_OVERTIME_SHARE, size=n),
        rng.uniform(*NON_FESTIVE_OVERTIME_SHARE, size=n),
    )
    overtime_hours = (grid["actual_hours"] * overtime_share).round(1)
    grid["overtime_hours"] = np.minimum(overtime_hours, grid["actual_hours"])

    return grid


def assign_labor_cost(grid):
    regular_hours = (grid["actual_hours"] - grid["overtime_hours"]).clip(lower=0)
    regular_pay = regular_hours * grid["hourly_rate"]
    overtime_pay = grid["overtime_hours"] * grid["hourly_rate"] * OVERTIME_MULTIPLIER
    wage_cost = regular_pay + overtime_pay
    overhead = wage_cost * LABOR_OVERHEAD_RATE
    grid["labor_cost"] = (wage_cost + overhead).round(2)
    return grid


def assign_sales_per_labor_hour(grid, rng):
    n = len(grid)
    weekly_noise = rng.uniform(0.85, 1.15, size=n)
    festive_mult = np.where(
        grid["is_festive_week"],
        rng.uniform(*FESTIVE_REVENUE_MULTIPLIER, size=n),
        1.0,
    )
    estimated_weekly_revenue = grid["base_weekly_revenue"].to_numpy() * weekly_noise * festive_mult

    safe_hours = grid["actual_hours"].replace(0, np.nan)
    grid["sales_per_labor_hour"] = (estimated_weekly_revenue / safe_hours).round(2).fillna(0.0)
    return grid


def build_staffing_ids(grid):
    grid = grid.sort_values(["date_key", "store_key"]).reset_index(drop=True)
    date_strs = grid["date_key"].dt.strftime("%Y%m%d")
    seq = date_strs.groupby(date_strs).cumcount() + 1
    grid["staffing_id"] = ["STF-" + d + "-" + f"{s:06d}" for d, s in zip(date_strs.to_numpy(), seq.to_numpy())]
    return grid


# =================================================
# VALIDATION
# =================================================

def validate_staffing(output, valid_store_keys, valid_dates):
    assert output["staffing_id"].is_unique, "Duplicate staffing_id detected."

    orphan_store_mask = ~output["store_key"].isin(valid_store_keys)
    assert not orphan_store_mask.any(), "Orphan store_key references detected in fact_staffing."

    orphan_date_mask = ~output["date_key"].isin(valid_dates)
    assert not orphan_date_mask.any(), "date_key values not present in dim_date detected in fact_staffing."

    assert (output["allocated_headcount"] > 0).all(), "Non-positive allocated_headcount detected."
    assert (output["actual_headcount"] > 0).all(), "Non-positive actual_headcount detected."
    assert (output["scheduled_hours"] > 0).all(), "Non-positive scheduled_hours detected."
    assert (output["actual_hours"] > 0).all(), "Non-positive actual_hours detected."
    assert (output["overtime_hours"] >= 0).all(), "Negative overtime_hours detected."
    assert (output["overtime_hours"] <= output["actual_hours"]).all(), "overtime_hours exceeds actual_hours."
    assert (output["labor_cost"] >= 0).all(), "Negative labor_cost detected."
    assert (output["sales_per_labor_hour"] >= 0).all(), "Negative sales_per_labor_hour detected."


# =================================================
# OUTPUT
# =================================================

REQUIRED_STAFFING_COLUMNS = [
    "staffing_id",
    "date_key",
    "store_key",
    "allocated_headcount",
    "actual_headcount",
    "scheduled_hours",
    "actual_hours",
    "overtime_hours",
    "labor_cost",
    "sales_per_labor_hour",
]


def finalize_staffing_output(grid):
    output = grid.copy()
    output["date_key"] = output["date_key"].dt.strftime("%Y-%m-%d")
    return output[REQUIRED_STAFFING_COLUMNS]


def print_validation_summary(output, grid):
    row_count = len(output)
    physical_store_count = grid["store_key"].nunique()

    festive_avg_ot = grid.loc[grid["is_festive_week"], "overtime_hours"].mean()
    non_festive_avg_ot = grid.loc[~grid["is_festive_week"], "overtime_hours"].mean()

    print("=" * 50)
    print("VALIDATION SUMMARY -- fact_staffing.csv")
    print("=" * 50)
    print(f"Total rows written:              {row_count:,}")
    print(f"Target rows (214 x 52):           {TARGET_ROWS:,}")
    print(f"Distinct physical stores:         {physical_store_count:,}")
    print(f"Distinct weeks:                   {grid['date_key'].nunique():,}")
    print(f"Avg overtime hours (festive):      {festive_avg_ot:,.2f}")
    print(f"Avg overtime hours (non-festive):  {non_festive_avg_ot:,.2f}")
    print("=" * 50)


# =================================================
# MAIN
# =================================================

def main():
    rng = np.random.default_rng(SEED)

    raw_stores, raw_dates = load_inputs()

    stores = prepare_physical_stores(raw_stores)
    if len(stores) != TARGET_PHYSICAL_STORES:
        print(
            f"NOTE: Found {len(stores)} physical stores in dim_store.csv "
            f"(expected {TARGET_PHYSICAL_STORES}). Proceeding with actual count."
        )

    weeks, valid_dates = prepare_weeks(raw_dates)
    if len(weeks) != TARGET_WEEKS:
        print(
            f"NOTE: Found {len(weeks)} weeks available for staffing generation "
            f"(expected {TARGET_WEEKS}). Proceeding with actual count."
        )

    stores = assign_store_level_attributes(stores, rng)

    grid = build_grid(stores, weeks)
    grid = assign_headcount(grid, rng)
    grid = assign_hours(grid, rng)
    grid = assign_labor_cost(grid)
    grid = assign_sales_per_labor_hour(grid, rng)
    grid = build_staffing_ids(grid)

    output = finalize_staffing_output(grid)

    valid_store_keys = set(stores["store_key"])
    validation_frame = output.copy()
    validation_frame["date_key"] = pd.to_datetime(validation_frame["date_key"])
    validate_staffing(validation_frame, valid_store_keys, valid_dates)

    out_path = os.path.join(os.path.dirname(_resolve_path(STORE_FILE)), STAFFING_OUTPUT_FILE)
    output.to_csv(out_path, index=False)

    print(f"fact_staffing.csv written to: {out_path} ({len(output):,} rows)")
    print_validation_summary(output, grid)


if __name__ == "__main__":
    main()
